language: node_js
nodejs:
  - node
services:
  - postgresql

install:
  - npm install

script:
  # - npm run test

notifications:
  slack: andela:E6PvFgt7ygC8QJHxXQJ7mEML
  webhooks: https://coverals.io/webhook 

env:
  - POSTGRES_CONNECTION_STRING=postgresql//travis@localhost:5432/travis_ci_test
  - DB_NAME=travis_ci_test
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_script:
 # -run after all script is executed successfully

 after_success:
  - run npm coverage

after_failure:
  # - run if any job fails