language: node_js
nodejs:
  - node
services:
  - postgresql

install:
  - npm install

script:
  # - npm run test

notifications:
  slack=${SLACK_ENV}
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_script:
 # -run after all script is executed successfully

 after_success:
  # - run all jobs is successfull

after_failure:
  # - run if any job fails