language: node_js
nodejs:
  - node
services:
  - postgresql

install:
  - npm install

script:
  # - npm run test

notifications:
  slack:
    secure: z2ARqeWunsGh607EufhMVV81GT3TmjwUJM9jKs/kC7LjDRM21JraTebWrjAMh5BcG+Cknk4YJKR92kcGNBX1L0HzhrHLe83AEa3qMjNdvwnHnVG4lUfmJ/5RPfuOYrBpFm0CW3e7PlNcXyD1OOfed3tHyOLK7nW4vuoEGdE3rBtmtNdwkx6eIU9Vl8hTwVKJi+PJQnFOZqFylMgsSEjBlY05g2SiOtAIRtr7908mrGvB9K0qExi3TwZ7dS0ppOjpGNJ16eb6Kf9JnH3aQJfifzQ6t8MM0raxmy4nMvtOMwZReIoZGjFZa2s9BAdVJPgwxaS2lv21FYgomS4TFboNDEagbUmI3O10Bz+EOgjpz1DJtyNpXG9UNWwH+kHxXToHKVxxdAeBF1bcYuuSQ9F/QJPzzbqUQkYsRZPtvEqOtdcB7Ke0MpyLB6zxpCxFvnti4iGCsnUQLwrGZYKGLZB1Z4P2Dht3Fw0+fR1RimURfqqCU1MyGb+wTuzpW8m6PG3ZgPiHUCUozBNd4DkSqjeNS2uBkP5TsIL9hWfB35yh/snM7xnzVT61my/+gWrWfs1dSIMF2wsH0/tlWHxxFbQ7q08Dv03hplP3Z9pcQtzEAc2eynS60xB9UDegG49F0UkB8GjaSO+LOTl6IX827fz7jD6AFhZlw3HC/0YuebZPd0g=
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_script:
 # -run after all script is executed successfully

 after_success:
  npm run coverage

after_failure: 
  # - run if any job fails

after_failure:
  # - run if any job fails

after_failure: 
  # - run if any job fails
