// import "./models/users.spec";
// import "./models/favourites.spec";
// import "./miscellaneous/miscellaneous.spec";
// import "./oauth/social.auth.spec";
// import "./models/articles.spec";
// import "./miscellaneous/emails/email.spec";
// import "./controller/user/signUp.spec";
// import "./controller/user/verification.spec";
// import "./controller/user/signIn.spec";
// import "./controller/user/profile.spec";
// import "./controller/user/resetPassword.spec";
// import "./controller/favorite/favorites.spec";
// import "./models/notifications.spec";
// import "./controller/article/article.spec";
// import "./controller/article/pagination.spec";

import "./models/users.spec";
import "./models/favourites.spec";
import "./miscellaneous/miscellaneous.spec";
import "./oauth/social.auth.spec";
import "./models/articles.spec";
import "./controller/user/verification.spec";
import "./controller/user/signIn.spec";
import "./controller/user/profile.spec";
import "./miscellaneous/emails/email.spec";
import "./controller/user/resetPassword.spec";
import "./controller/favorite/favorites.spec";
import "./models/notifications.spec";
import "./controller/article/article.spec";
import "./controller/article/pagination.spec";
import "./controller/user/signUp.spec";
